//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gorsel_ProgramlamaEntities : DbContext
    {
        public Gorsel_ProgramlamaEntities()
            : base("name=Gorsel_ProgramlamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Kitaplar> tbl_Kitaplar { get; set; }
        public virtual DbSet<tbl_İngilizce> tbl_İngilizce { get; set; }
        public virtual DbSet<tbl_login> tbl_login { get; set; }
    }
}
