//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emanetlerrr
    {
        public int EmanetID { get; set; }
        public Nullable<int> EmanetKitapID { get; set; }
        public string EmanetÜyeTC { get; set; }
        public Nullable<System.DateTime> EmanetVerilenTarih { get; set; }
        public Nullable<System.DateTime> EmanetAlınacakTarih { get; set; }
        public Nullable<bool> EmanetDurum { get; set; }
    
        public virtual tbl_Kitap tbl_Kitap { get; set; }
        public virtual tbl_Uyee tbl_Uyee { get; set; }
    }
}
